### ISSUE TITLE
Add number of new tickets next to 'Tickets' label

### ISSUE THREAD

**Issue by kakoma** [kanzucode/kanzu-support-desk#63]
Similar to how plugins show update count, show number of new tickets next to the _Tickets_ label

![plugin_update_count](https://cloud.githubusercontent.com/assets/1725251/18607033/3332224a-7cc9-11e6-8b33-aaf51353c81b.png)

**Comment by ssebaggala** [comment]
Number of new tickets added next to Tickets menu
