### ISSUE TITLE
Some phrases don't translate

### ISSUE THREAD

**Issue by kakoma** [kanzucode/kanzu-support-desk#69]
While translating into French, WP user @csertelet noticed that some phrases don't translate. 

> In the client form (I use ticket publishing without login first : customer registration is disabled) :
> – the select lists names (Severity, Product and Category) are not translated,
> – the error messages “Please enter a valid email address.” and “This field is required.” either.
> 
> In the admin section (less annoying) :
> – in the “all tickets” list :
> – the “Open” filter stays in english, others not.
> – status stay in english : draft, open, …
> – severities levels either : low, high, …
> – in settings / global :
> – the 6 buttons “Add New Agent”, “View Agents”, “Add New Supervisor”,… stay in english
> – the button “Generate Debug File” either

Details here: https://wordpress.org/support/topic/translation-some-words-stay-in-english/

**Comment by ssebaggala** [comment]
List of un translated strings

grep -r '_(' ./ | grep -v 'kanzu-support-desk' && grep -r '_e(' ./ | grep -v 'kanzu-support-desk'

...

**Comment by ssebaggala** [comment]
Fixed. 

https://github.com/kanzucode/kanzu-support-desk/commit/fb194074dbcc51943a644a26b17e1bb0d2c86a0f
